FROM python:3.10.6-alpine

WORKDIR /usr/src

COPY requirements.txt .


ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update 
RUN apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY entrypoint.sh .
RUN chmod +x /usr/src/entrypoint.sh


COPY . .

ENTRYPOINT ["sh", "entrypoint.sh"]


